### ISSUE TITLE
[스프린트 #9] 데이터 레이블링 수정 작업에 따른 백엔드 API 데이터 수정 요청

### ISSUE THREAD

**Issue by edit8080** [DSC-University-of-Seoul/2021-spring-project#102]
# 기능 Issue 

Linked Feature backlog : #KDSK-105

## 필요한 기능

- 데이터 레이블링 수정 작업에 따라 백엔드 API 데이터의 속성 추가 작업이 필요합니다.
- 기존의 anomaly 테이블과 Join 및 Count 작업을 수행하면 달성할 것으로 예상되어 DB 스키마의 변경은 없을 것으로 예상됩니다.

### 수정 전
- /districts (도,광역시 / 시,군,구)
```
district_code,
district_name,
parent_code,
count // 이상행동 건수
```

- /centers (어린이집)
```
center_id,
center_name,
operation_type,
operation_status,
zip_code,
address,
center_phone,
fax,
web_page,
latitude,
longitude,
district_code,
district_name
```

### 수정 후
- /districts (도,광역시 / 시,군,구)
```
district_code,
district_name,
parent_code,
assualt_count, // 구역 폭행 건수 (추가)
fight_count, // 구역 싸움 건수 (추가)
swoon_count, // 구역 실신 건수 (추가)
anomaly_count // 구역 이상행동 건수 (속성명 변경)
```
- /centers (어린이집)
```
center_id,
center_name,
operation_type,
operation_status,
zip_code,
address,
center_phone,
fax,
web_page,
latitude,
longitude,
district_code,
district_name
assualt_count, // 어린이집 폭행 건수 (추가)
fight_count, // 어린이집 싸움 건수 (추가)
swoon_count, // 어린이집 실신 건수 (추가)
anomaly_count // 어린이집 이상행동 건수 (추가)
```

## 담당자 할당 확인

담당자
- [x] @rxdcxdrnine 

## 우선순위 확인
요청자의 예상 우선순위 : 상
- [x] 담당자의 우선순위 확인 
- [x] PM의  최종 우선순위 확인

**Comment by rxdcxdrnine** [comment]
@edit8080 

늦었지만 질문있습니다..!

1. 현재 pivoting 을 이용해 집계할 때 anomaly_log 테이블에 폭행/싸움/실신/전체 레이블의 값이 최소한 1개 있어야 SQL 쿼리 오류가 나지 않습니다.
anomaly_log 테이블 전체에서 각 레이블이 1개씩만 있으면 되는데, 이 부분이 보장될까요?
2.  /districts API 에는 적용했는데, /centers API 에도 필수적으로 있어야 하나요?
/centers API 는 SQL 쿼리가 훨씬 복잡할 것 같아 질문드립니다.

**Comment by edit8080** [comment]
1. 집계할 때 데이터가 없으면 NULL로 처리할 수 없는건가요?
2. 아래 PR 작업에서 이상행동이 발생한 어린이집 마커를 클릭할 때 발생한 건수 정보를 사용자에게 제공하는 기능을 구현했습니다. 해당 작업을 진행할 때 /centers 의 `assult_count, fight_count, swoon_count, anomaly_count` 값을 사용하고 있어서 필수적으로 있어야 할 것 같습니다.

https://github.com/DSC-University-of-Seoul/2021-spring-project/pull/101#issuecomment-886178951

**Comment by rxdcxdrnine** [comment]
1. 찾아봤는데 아래 링크와 같이 처리하면 될 수 있을 것 같습니다.
https://stackoverflow.com/questions/48792579/count-group-by-enum-including-possible-enum-values-that-have-0-count
2. 필수적이라면 `/centers` 에도 해당 값들이 출력될 수 있도록 하겠습니다.

말씀해주신대로 현재 테이블 간의 관계를 이용해 anomaly_log 테이블의 정보를 집계해 출력하고 있습니다.
`/centers` 에서 데이터를 출력하는 데에도 sql 문을 처리하는데 시간이 걸릴 것 같습니다!
