### ISSUE TITLE
[스프린트 #8] 데이터 포맷 지정 확인

### ISSUE THREAD

**Issue by YubeenSon** [DSC-University-of-Seoul/2021-spring-project#79]
# 기능 Issue 

## 필요한 기능
dummy data 삽입 전 데이터 포맷에 대한 확인을 합니다

## 설명 
cctv
|컬럼명|포맷|예시|
|------|---|-------|
|cctv_id|uuidv4|004aadf4-8e1a-4450-905b-6039179f52da|
|cctv_name|공간명_위치(혹은 번호)|참새반_1|
|cctv_mac|12자리|54C4153B5737|
|quality|enum|HD|
|install_date|YY/MM/DD|21/07/07|
|uninstall_date|YY/MM/DD|22/07/07|
|center_id|11자리|11620000341|

video
|컬럼명|포맷|예시|
|------|---|-------|
|video_id|uuidv4|004aadf4-8e1a-4450-905b-6039179f52da|
|record_date|생성 YY/DD/MM|21/09/01|
|storage_name|DVR 이름|한화테크윈 HRX-421|
|cctv_id|uuidv4|004aadf4-8e1a-4450-905b-6039179f52da|

anomaly
|컬럼명|포맷|예시|
|------|---|-------|
|anomaly_id|autoIncrement|1|
|anomaly_type|enum|폭행|
|start_time|HH:MM:SS|12:04:31|
|end_time|HH:MM:SS|12:04:50|
|follow_up|enum|이상행동감지|
|video_id|uuidv4|004aadf4-8e1a-4450-905b-6039179f52da|

log
|컬럼명|포맷|예시|
|------|---|-------|
|anomaly_log_id|autoIncrement|1|
|center_id|11자리|11620000341|
|center_name|string(150)|ABC어린이집|
|address|string(150)|서울시 동대문구 ~|
|record_date|YY/MM/DD|21/07/07|
|anomaly_type|enum|폭행|

DVR 구매 후 변경되는 사항이 생길 수 있습니다.
수정되야 할 부분 있으면 comment 부탁드립니다!

## 담당자 할당 확인
 
(작업 예상) 담당자: @handal95 
- [ ] 담당자 접수 확인

## 우선순위 확인
요청자의 예상 우선순위 : 상
- [ ] 담당자의 우선순위 확인 ( 필요시 우선순위 수정 ) 
- [x] PM의  최종 우선순위 확인 

###
작업을 시작한 작업자는 해당 PR 의 번호를 댓글에 등록

**Comment by handal95** [comment]
해당 이슈 아직 수정사항이 남아있나요?

**Comment by YubeenSon** [comment]
수정 사항은 없고 모델은 모두 auto increment로 형식이 지정되어있어 추후에 모델 수정 후 uuid 적용시키려합니다. 
포맷 지정 관련해 수정사항은 없습니다!
