### ISSUE TITLE
[버그 리포트] 어린이집 데이터 fetch 오류

### ISSUE THREAD

**Issue by YubeenSon** [DSC-University-of-Seoul/2021-spring-project#93]
# 버그 리포트 Issue 
제주도, 세종시 어린이집 데이터가 제대로 불러와지지 않습니다.
## 설명
- 어린이집 데이터에서도 시군구코드, 어린이집 코드를 갱신하지 않아 시군구코드가 옛날 코드로 들어간 것 같습니다.

## Steps to reproduce 
 1. 지도에서 제주도 어린이집 갯수를 확인한다
 2. 지도에서 세종시 어린이집 갯수를 확인한다
 
## 버그 발생 시 발생하는 작업 (BUG)

- 제주도 어린이집 개수가 2개로 표시됩니다. (이 또한 어떻게 된 일인지 허허허)
 
## 버그 수정 후 의도되는 작업 (correct)

- 세종시와 제주시에 원래의 어린이집 갯수가 다 찍히는 것(제주도의 경우 732)

## 담당자 할당 확인

 
(작업 예상) 담당자: @YubeenSon 
- [x] 담당자 접수 확인

## 우선순위 확인
요청자의 예상 우선순위 :  
- [ ] 담당자의 우선순위 확인 ( 필요시 우선순위 수정 ) 
- [x] PM의  최종 우선순위 확인

###

작업을 시작한 작업자는 해당 PR 의 번호를 댓글에 등록

**Comment by YubeenSon** [comment]
메인으로 쓰던 db인 kidskeeper가 알 수 없는 이유로 기능을 하지 못해
kidskeeper_main db를 새로 생성하여 제주 ,세종시 데이터를 삽입하였습니다.
(세종시..브랜치 탈출해버렸습니다..)

제주시는 확인해보니 district_code는 현 시군구코드(ex.5011000000)로 잘 들어가있어 문제를 조금 더 찾아봐야 할 것 같습니다..
제주시 데이터가 보이지 않는 문제는 스프린트 9에서 bug fix로 다시 다루도록 하겠습니다.

**Comment by YubeenSon** [comment]
@rxdcxdrnine 
창구님 프론트에 child_care_center 정보가 하나도 보이지 않는데 확인 부탁드립니다..!

**Comment by edit8080** [comment]
@YubeenSon 
지금 배포한 웹 사이트는 이상행동 데이터에 맞게 어린이집 마커가 출력되도록 만들어서 관련 정보가 보이지 않을 겁니다.
자세한 작업 내용은 다음 PR을 확인해주세요
https://github.com/DSC-University-of-Seoul/2021-spring-project/pull/101#issuecomment-886178951

필요하시다면 이전 코드를 기반으로 배포해드리겠습니다. 😀

**Comment by YubeenSon** [comment]
@edit8080 
지금의 PR이 닫힌 후에 이전 코드 기반으로 배포해주실 수 있나요?
Review가 끝난 후 연결 확인하겠습니다!

**Comment by edit8080** [comment]
이전 코드 기반한 임시 웹 사이트입니다!

http://kids-keeper-tmp.s3-website.ap-northeast-2.amazonaws.com/monitoring

**Comment by YubeenSon** [comment]
이제 프론트에서 어린이집별 조회가 아닌 사건/사고별 조회로 바뀜에 따라
다음 스프린트에 제주도 seeder 추가를 통해 제주도 어린이집 정보가 fetch되지 않는 문제를 해결하려합니다.

**Comment by YubeenSon** [comment]
구
![image](https://user-images.githubusercontent.com/65553480/129192752-37e8393b-c643-4f6e-b252-78c425c22e3a.png)
현
![image](https://user-images.githubusercontent.com/65553480/129192773-8124921e-2f59-4a7e-9a2e-432b821b6b65.png)
이슈 해결되었습니다!

**Comment by YubeenSon** [comment]
세종시 또한 bug fix 완료되었습니다!
![image](https://user-images.githubusercontent.com/65553480/129192946-6bb8671a-844e-413d-b97d-fe4e1cff892e.png)
