### ISSUE TITLE
[스프린트 #8] backend hub 연계

### ISSUE THREAD

**Issue by rxdcxdrnine** [DSC-University-of-Seoul/2021-spring-project#99]
# 기능 Issue 

## 필요한 기능
hub 에서 backend 서버에 HTTP REST API를 이용한 요청으로 이상행동 테이블에 데이터를 추가합니다.

## 설명 
아래 데이터 샘플의 형태로 request body 를 담아 데이터를 전송합니다.

```json
{
    "video": {
        "record_date": "2021-07-17 21:00:00",
        "cctv_mac": "125454545460",
        "storage_name": "data/cctv1/"
    },
    "anomaly_type": "폭행",
    "start_time": "2021-07-17 00:00:00",
    "end_time": "2021-07-17 01:00:00"
}
```

아래 링크의 swagger를 통해 테스트 데이터를 넣어 데이터가 입력되는지 확인할 수 있습니다.
http://ec2-13-124-81-25.ap-northeast-2.compute.amazonaws.com:3000/api/docs/#/anomaly%20log/post_anomalies_logs

## 담당자 할당 확인
 
(작업 예상) 담당자: @owao 
- [x] 담당자 접수 확인

## 우선순위 확인
요청자의 예상 우선순위 :  
- [x] 담당자의 우선순위 확인 ( 필요시 우선순위 수정 ) 긴급
- [x] PM의  최종 우선순위 확인 

###
작업을 시작한 작업자는 해당 PR 의 번호를 댓글에 등록

**Comment by handal95** [comment]
Issue 마무리 되었나요?
